### PR TITLE
feat: use lunchpail needs to install minio

### PR DESCRIPTION
**Pull request by aavarghese**

### CODE REVIEW

**Review by starpit — APPROVED** [review]
lgtm

**Comment by aavarghese** [comment]
Need to find out why these tests are failing with `Error: exit status 1`. None of these tests fail locally on macos so will have to reproduce GHA like ubuntu env...

**Comment by starpit** [comment]
why did we change the wget install of minio to one that is debian-specific? and also one that (by use of apt) requires root access?

**Review by starpit — CHANGES_REQUESTED** [review]
why did we change the wget install of minio to one that is debian-specific? and also one that (by use of apt) requires root access?

**Comment by aavarghese** [comment]
> why did we change the wget install of minio to one that is debian-specific? and also one that (by use of apt) requires root access?

I was seeing `wget command not found` error exit status 1 in some cases...

**Comment by starpit** [comment]
Strange? We have been using it in gha till now? Did you see this for local
or kubernetes?

**Review by starpit — APPROVED** [review]
lgtm

**Pull request merged**
