### PR TITLE
feat: enqueue --wait returns task exit code

### LINKED ISSUE #145: feat: `lunchpail enqueue file --wait` should have exit code to match that of the task
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by aavarghese**
Covered by `test7f-wait`

Fixes #145

### CODE REVIEW

**Review by starpit — CHANGES_REQUESTED** [review]
Don't we want to `os.Exit()` based on the content of the `code` file? That is at least what #145 states.

**Comment by aavarghese** [comment]
```
Done with /queue/processing/task.2.txt
ls: test/test7/test7: No such file or directory
Processing 0 /queue/processing/task.6.txt
Done with /queue/processing/task.6.txt
ls: test/test7/test7: No such file or directory
```
Looking into this err above..

**Review by starpit — APPROVED** [review]
lgtm

**Comment by aavarghese** [comment]
Will need to modify test scripts to work with multiple task failures with different RCs (Todo in a separate PR) 
/cc @starpit

**Pull request merged**
